name: timeflux
dependencies:
- python>=3.6.7
- networkx>=2.1
- pyyaml>=3.13
- numpy>=1.15
- pandas>=0.23.4
- xarray>=0.11
- bottleneck
- scipy>=1.1
- pyzmq>=17.1.2
- coloredlogs>=10.0
- pytables>=3.4.4
- pytest>=4.0.2
- sphinx>=1.8
- sphinx_rtd_theme
- pip
- pip:
  - pylsl==1.10.5
  - python-dotenv==0.10.1
  - python-osc==1.7.0
  - git+https://github.com/timeflux/timeflux
  - git+https://github.com/timeflux/timeflux_example
