name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    - name: Test formatting
      run: |
        pip install black
        black --check timeflux
    - name: Test documentation
      run: |
        cd doc
        make html
        cd ..
    - name: Test code
      run: |
        pip install git+https://github.com/timeflux/timeflux_example
        pip install pytest pytest-cov
        # Ignore MNE tests as it is a heavy dependency and will soon be removed from core
        pytest --cov=timeflux -k "not mne"
